### ISSUE TITLE
DimensionalityError: Cannot convert from 'inch' to 'megamolar'range_unit set by theme is not compatible with data units

### ISSUE THREAD

**Issue by kinverarity1** [geopozo/pozo-py#30]
Thank you for creating and sharing this package - it is wonderful 🎆  

I encountered an error which I think has something to do with the theme, as recommended on the README. 

This code works fine in rendering a track:

```
las = lasio.read("654014.las")
graph = pozo.Graph(las, include=['CALI'])
graph.render()
```

However if I add in the theme as recommended on the README:

```
las = lasio.read("654014.las")
graph = pozo.Graph(las, include=['CALI'])
graph.set_theme("cangrejo")
graph.render()
```

This error occurs:

```
---------------------------------------------------------------------------
DimensionalityError                       Traceback (most recent call last)
Cell In[46], line 1
----> 1 graph.render()

File C:\devapps\syski\mambaforge\envs\py310\lib\site-packages\pozo\graphs.py:93, in Graph.render(self, **kwargs)
     91 if xp is True: # noqa this can also but something that evals to True but is not exactly true
     92     kwargs["xp"] = self.xp
---> 93 self.last_fig = self.renderer.render(self, **kwargs)
     94 return self.last_fig

File C:\devapps\syski\mambaforge\envs\py310\lib\site-packages\pozo\renderers\plotly.py:808, in Plotly.render(self, graph, static, depth, xp, **kwargs)
    803 color_lock = kwargs.pop("color_lock", {})
    804 # kwargs: theme_override, override_theme (same thing)
    805 
    806 # this generates XP layout too, I don't love, would rather set axes
    807 # separating XP from here would be good but let's call it techdebt
--> 808 layout = self.get_layout(graph, xp=xp, depth=depth, **kwargs)
    809 posmap = self._last_posmap
    810 # what arguments do we need here now

File C:\devapps\syski\mambaforge\envs\py310\lib\site-packages\pozo\renderers\plotly.py:411, in Plotly.get_layout(self, graph, xp, **kwargs)
    409     data_unit = trace.get_unit()
    410     if not (data_unit is None or range_unit is None or range_unit.is_compatible_with(data_unit)):
--> 411         raise pint.DimensionalityError(range_unit, data_unit, extra_msg="range_unit set by theme is not compatible with data units")
    412 themes.pop()
    413 if y_unit is not None and trace.get_depth_unit() is not None:

DimensionalityError: Cannot convert from 'inch' to 'megamolar'range_unit set by theme is not compatible with data units
```

It does not occur if other mnemonics are selected:

```
las = lasio.read("654014.las")
graph = pozo.Graph(las, include=['TEMP'])
graph.set_theme("cangrejo")
graph.render()
```

The LAS file is attached here:

[654014.las.txt](https://github.com/geopozo/pozo-py/files/15227525/654014.las.txt)

If this is by design, I suggest adding a note on the README that themes will raise Exceptions unless the data is 'clean', and to explain what that means.

Again, thanks for this package!

**Comment by ayjayt** [comment]
ooh our first outside issue! 😭 I will take a look tonight!

**Comment by ayjayt** [comment]
Hi @kinverarity1,

```python
las = lasio.read("654014.las")
graph = pozo.Graph(las, include=['CALI'], unit_map={"CALI":"millimeter"})
graph.set_theme("cangrejo")
graph.get_axis("CALI").set_theme({"range_unit":"millimeter", "range": [100, 175]}) # optional, set range
graph.render()
```

The issue is that LAS files often show millimeter as MM but in SI units that means megamolar, so we have to override the default unit in line 2.

I will improve that behavior to be more automatic and the theme behavior for tomorrow.

You can also use

`pozo.units.check_las(las)` to see what pozo is seeing:

![image](https://github.com/geopozo/pozo-py/assets/30324885/2d14bd42-51cf-4e5d-be27-58773c2d5b36)

**Comment by ayjayt** [comment]
Some unit attributes are:

{
        "color" : "red",
        "range": [0.2, 2000],                 # a list
        "scale": "log",                             # only option
        "range_unit":  "ohm * meter" # maybe set to None if no unit is parsed?
        "track_width": 200,
}

**Comment by kinverarity1** [comment]
Nice - thanks for the explanation. I didn't realise the theme was applying defaults in that manner, but that makes a lot of sense.

**Comment by ayjayt** [comment]
It's 'cause the theme specifies the `range` and the  `range_units`, and it
tries to convert the range to the units you have specified in the LAS file.
